# Generated by Django 4.1.7 on 2026-03-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activities',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workouts',
        ),
    ]
