# Generated by Django 4.1.7 on 2026-03-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_alter_activity_table_alter_team_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='team',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workout',
            table=None,
        ),
    ]
